### ISSUE TITLE
formValidate doesn't remove requirement for parent group in Civi 4.5

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/org.civicrm.multisite#1]
[Note to Eileen:  I know this isn't your problem if I'm not paying you!  I'm going to try to make time to write this patch myself, but I wanted to report this as a known issue for you or anyone else who comes across it.]

In Civi 4.5, the group "settings" page comes up in a snippet, which handles validation client-side - so hook_formValidate never fires.  So editing a group with this extension installed throws a validation error if you try to save a group without setting a parent.

The workaround is to open group settings in a new tab - the long-term fix is to call hook_buildForm instead of hook_formValidate to unset the parent group being required.

**Comment by eileenmcnaughton** [comment]
Ah yes that makes sense - we haven't used this with 4.5 yet - but when we do I'll sort that out ... unless  you do first :-)

**Comment by eileenmcnaughton** [comment]
Seamus fixed with #2
