### ISSUE TITLE
is_transactional only works when true?

### ISSUE THREAD

**Issue by JKingsnorth** [eileenmcnaughton/org.civicrm.multisite#14]
I wasn't able to get the API call to create a domain to work unless I set
is_transactional to "FALSE" - which I suppose is actually a TRUE value.

Is the instruction in the README now out of date?

**Comment by eileenmcnaughton** [comment]
Erm.... maybe.... can't remember any of this stuff anymore

**Comment by JKingsnorth** [comment]
Lol, fair enough, we're doing some work on investigating whether to switch to a multisite setup =]

**Comment by eileenmcnaughton** [comment]
For permissions reasons?
