### ISSUE TITLE
Membership types no longer visible cross-domain

### ISSUE THREAD

**Issue by johntwyman** [eileenmcnaughton/org.civicrm.multisite#26]
[This commit](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/PseudoConstant.php#L1528), introduced in Civi core 5.24, means that calls to the API are now domain-specific. This has changed the behaviour of calls to Membership.getoptions relating to Membership Types.

Where the Membership Type field in forms like Advanced Search and Find Members would display all available types across all domains, it now shows only those types defined in the active domain.

**Comment by johntwyman** [comment]
I've raised a PR #27 to address this issue.

**Comment by eileenmcnaughton** [comment]
Gitlab .... https://lab.civicrm.org/extensions/multisite
