### ISSUE TITLE
Reverting the commit to add the "v" to info.xml

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/org.civicrm.multisite#5]
I realized a couple of days ago that I'd screwed up the download URL when publishing this extension, so someone who tried downloading this extension through the civi UI would get an error.

I fixed it tonight, ran a test, and saw this:
![selection_060](https://cloud.githubusercontent.com/assets/1796012/9672301/78c048b0-5267-11e5-8b27-1a1c4b440bf4.jpg)

Thought you should know!

**Comment by eileenmcnaughton** [comment]
hmm - so the latest is 2.4 with tag 2.4 isn't it - do we need to increment again?
