### ISSUE TITLE
Core vs extension?

### ISSUE THREAD

**Issue by nganivet** [eileenmcnaughton/org.civicrm.multisite#7]
The multisite_custom_tabs_restricted is a nice addition to the extension, but change the focus of this extension from multi-site permissionning as it was before.

Some other additions to multi-site have been included in core (ie. event_price_set_per_domain). I am also about to add new features to multisite.

This leads to the core vs extensions debate for multi-site.

IMO this extension makes little sense and all should be in core as so central to civicrm and with no performance impact if not activated.

On a side note the multisite_custom_tabs should also enhanced through using a civicrm_domain_entity table as discussed for events. I might tackle that when done with the events.

**Comment by eileenmcnaughton** [comment]
I guess it would be good if it were an extension that shipped with core - that would give the advantage of it being tested without actually adding to core. I guess we need to make sure we keep making it easier to do things in extensions

**Comment by eileenmcnaughton** [comment]
NB - I'm not very vested in this - feel free to take it over
