### ISSUE TITLE
Issues when multisite is installed by not enabled

### ISSUE THREAD

**Issue by nganivet** [eileenmcnaughton/org.civicrm.multisite#9]
If the multisite extension is installed but not enabled (checkbox in the setting screen, and selecting an organization), then the action menu on search results only has 5 entries 
![actions-menu](https://cloud.githubusercontent.com/assets/3435067/19059897/aad88d6e-89a0-11e6-8702-29c68b797753.png).

Also none of the groups are visible to the end user in the groups tab (even though they are visible in the Manage Groups screen).

**Comment by eileenmcnaughton** [comment]
how does that happen??? If it's not enabled

**Comment by nganivet** [comment]
I know and have the fix (took me a while to find this out - hint: it's a hook). Will submit PR in a few minutes.

**Comment by eileenmcnaughton** [comment]
cool

**Comment by seamuslee001** [comment]
Looks like this was resolved via https://github.com/eileenmcnaughton/org.civicrm.multisite/pull/10
